package report

import (
	"fmt"
	"os"
	"path/filepath"
)

// FilesV1 lists the persistent report files generated by CLI v1.
type FilesV1 struct {
	HTML     string
	Markdown string
	JSON     string
}

// WriteFiles writes all report formats to dir.
func WriteFiles(dir string, rep Report) (FilesV1, error) {
	if err := os.MkdirAll(dir, 0750); err != nil {
		return FilesV1{}, fmt.Errorf("create report directory: %w", err)
	}

	files := FilesV1{
		HTML:     filepath.Join(dir, "report.html"),
		Markdown: filepath.Join(dir, "report.md"),
		JSON:     filepath.Join(dir, "report.json"),
	}

	if err := writeFile(files.HTML, func(file *os.File) error {
		return WriteHTML(file, rep)
	}); err != nil {
		return FilesV1{}, err
	}

	if err := writeFile(files.Markdown, func(file *os.File) error {
		return WriteMarkdown(file, rep)
	}); err != nil {
		return FilesV1{}, err
	}

	if err := writeFile(files.JSON, func(file *os.File) error {
		return WriteJSON(file, rep)
	}); err != nil {
		return FilesV1{}, err
	}

	return files, nil
}

func writeFile(path string, write func(*os.File) error) error {
	file, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0600) // #nosec G304 - the operator selects the report directory
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}

	if err := write(file); err != nil {
		if closeErr := file.Close(); closeErr != nil {
			return fmt.Errorf("write %s: %w; close file: %v", path, err, closeErr)
		}

		return fmt.Errorf("write %s: %w", path, err)
	}

	if err := file.Close(); err != nil {
		return fmt.Errorf("close %s: %w", path, err)
	}

	return nil
}
